import ThemeCustomization from '@/themes/index';
import Provider from '@/redux/provider'
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <Provider>
          <ThemeCustomization>
            {children}
          </ThemeCustomization>
        </Provider>
      </body>
    </html>
  );
}
